apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../shared-configs
- ../../../base/api-gateway


patches:
- path: replica-patch.yaml
- path: resource-patch.yaml

images:
- name: api-gateway
  newTag: stable  