apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "128Mi"    # ⬆️ More memory in production
            cpu: "100m"
          limits:
            memory: "256Mi"    # ⬆️ Higher limits in production
            cpu: "200m"