apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - elasticsearch/deployment.yaml
  - elasticsearch/service.yaml
  - elasticsearch/configmap.yaml
  - kibana/deployment.yaml
  - kibana/service.yaml
  - filebeat/daemonset.yaml
  - filebeat/configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: elk-stack
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  description: "ELK Stack for application logging and monitoring"