apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  template:
    spec:
      containers:
      - name: task-service
        resources:
          requests:
            memory: "128Mi"    # ⬆️ More memory for task operations
            cpu: "100m"
          limits:
            memory: "256Mi"    # ⬆️ Higher limits for task service
            cpu: "200m"