apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/name: kibana
  ports:
  - port: 5601
    targetPort: 5601
    name: http
  type: ClusterIP