apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  POSTGRES_HOST: "psql-taskmanager-prod.postgres.database.azure.com" 
  POSTGRES_DB: "taskmanager_production"  
  POSTGRES_SSL_MODE: "require"