apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production


resources:
- ../shared-configs
- ../../../base/auth-service

patches:
- path: replica-patch.yaml
- path: resource-patch.yaml

images:
- name: auth-service
  newTag: stable