apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-platform
  namespace: argocd
  labels:
    app: microservices-platform
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/blacksoxx/azure-go-task-manager.git  # ⚠️ Update this!
    targetRevision: HEAD
    path: k8s/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true